#FROM adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine-slim as java11
#FROM adoptopenjdk/openjdk16:jdk-16.0.1_9-alpine-slim as java16
FROM twdps/circleci-executor-builder:slim-1.2.0

LABEL maintainer=<carl.nygard@thoughtworks.com>

USER root

# packages required for use as a circleci remote-docker primary container
#        docker-compose~=1.27.4-r0 \
#        python3=3.9.2-3 \
# hadolint ignore=DL3003,DL3004
RUN echo "deb http://deb.debian.org/debian unstable main non-free contrib" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
        shellcheck=0.7.2-2+b1 \
        colordiff=1.0.18-1.1 \
        openjdk-17-jdk=17+35-1 \
        openjdk-16-jdk=16.0.2+7-2 \
        openjdk-11-jdk=11.0.12+7-2 \
        python3-pip=20.3.4-4 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir cookiecutter==1.7.3 && \
    pip install --no-cache-dir mkdocs==1.2.2 && \
    npm install -g @stoplight/spectral-cli@6.1.0 && \
    wget -q -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64 && \
    chmod +x /usr/local/bin/hadolint && \
    ln -s /usr/bin/shellcheck /usr/local/bin/

# packages required for use as a circleci java primary container
#RUN apk add --no-cache \
#    openjdk11==11.0.11_p9-r0 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community

#COPY --from=java16 /opt/java/openjdk /usr/lib/jvm/java-16-openjdk
#COPY --from=java11 /opt/java/openjdk /usr/lib/jvm/java-11-openjdk

USER circleci

WORKDIR /home/circleci/project

HEALTHCHECK NONE
